format = """
$username\
$hostname\
$directory\
$git_branch\
$cmd_duration\
$line_break\
$character"""

[directory]
style = "blue"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
